### PR TITLE
Add debug CSS function

### PR DESCRIPTION
**Pull request by paulfarino**
In console write `debugCss()`

It will outline all elements on the current page. This could be a useful utility to debug CSS or to show the structure of a component. Thoughts?

[](https://postimg.org/image/ygkoo0jmr/)

### CODE REVIEW

**Comment by mattrothenberg** [comment]
This looks great, @paulfarino.

Two philosophical questions to consider before merging.
1. If designers are at the point of contributing code to a living style guide, do you think they're past the point of debugging / drilling into pesky layout problems? Ideally, the code that gets added to the style guide has been battle tested and is "bug free." Might it weird out users to have the ability to "debug" CSS that's ostensibly ready for production? What's the use case?
2. My gut tells me this functionality would be better accessed through a Chrome extension or bookmarklet. I don't think the global JS function is very discoverable, and I'm not convinced that it's the responsibility of the styleguide to provide debugging tools.

**Comment by mattrothenberg** [comment]
Bookmarklet implementation as per http://mrcoles.com/bookmarklet/

```
javascript:(function()%7B%5B%5D.forEach.call(document.querySelectorAll(%22*%22)%2Cfunction(a)%7Ba.style.outline%3D%221px%20solid%20%23%22%2B(~~(Math.random()*(1%3C%3C24))).toString(16)%7D)%7D)()
```

**Comment by paulfarino** [comment]
I agree.
Interesting note: I've seen various implementations of debugging css. [Setting a flag](https://github.com/minamarkham/sassy-starter/blob/master/src/scss/libs/_pesticide.scss) in css is another implementation that could be useful outside of this repo. It allows you to see the debug css on any route vs your current route.

**Comment by mattrothenberg** [comment]
That's a really novel use of Sass variables 👍.

I would definitely be interested in a more robust use of Sass features in
this style guide (mixins, etc)

**Pull request closed without merging**
